### ISSUE TITLE
Trigger onNextStep method with custom button

### ISSUE THREAD

**Issue by berserkerChrist** [colbymillerdev/react-native-progress-steps#16]
I'd like to know if there's a way to trigger onNextStep method with a custom View element that's inside a step

Example:  

<View onPress={ //onNextStep() call goes here }>
   //Element
</View>

Thanks!

**Comment by jeyarruda** [comment]
https://github.com/colbymillerdev/react-native-progress-steps/issues/15#issuecomment-556167242

And in this case, you can change only the state of progress step with your custom view 👍 🇧🇷
