### ISSUE TITLE
Axios request change currentStep

### ISSUE THREAD

**Issue by zapcriativo** [colbymillerdev/react-native-progress-steps#24]
Hi, 

I have a ajax call with axios, when return complete i need to change current step, But in changing the state nothing happens. How can I do this?

**Comment by chathuraedirisingh** [comment]
Same here. I declared & init activeStep in state and increment the value on next button press. after submit i want to go to first step(index = 0).  But nothing happens.

**Comment by harishchopra86** [comment]
You can do this by creating a reference of progress steps.
Declare a progressSteps variable like this in your component:
```
  progressSteps: any

```

Then in render method create reference to this variable like as follows:
```
<ProgressSteps
          ref={(ref: any) => { this.progressSteps = ref }}
        >
</ProgressSteps>
```

Then you can set active step like this

```
    this.progressSteps.setActiveStep(1)

``` 

I don't know if this is right method or not but I have done it this way.

**Comment by hanaechahid** [comment]
Hi, I have the same problem, I call an axios request when I click next button when the request returns a success response I change the errors props to false to pass to the next step but didn't work I need to click on it many times then it passes to the next.

@zapcriativo, @harishchopra86 @chathuraedirisingh  did you solve the problem?

**Comment by colbymillerdev** [comment]
Hello Everyone - Can you please post any code snippets that can help with debugging this issue?
