### ISSUE TITLE
how to change icon on complete step and how to change border style on progress line

### ISSUE THREAD

**Issue by LucasHimelfarb** [colbymillerdev/react-native-progress-steps#25]
how to change icon on complete step and how to change border style on progress line...

I need to achieve something like that...

![this](https://user-images.githubusercontent.com/46998551/71184688-e6086e00-2258-11ea-84f7-f20f5db395a4.png)

**Comment by LucasHimelfarb** [comment]
how to change icon on complete step and how to change border style on progress line

**Comment by colbymillerdev** [comment]
Currently the icon on a completed step can't be changed. However, this feature is planned to be implemented in a future release. I will let you know once that functionality is available.

For the border style, there is a current issue with React Native that's preventing it from being changed. I am looking into it now and will hopefully have a workaround/solution shortly.
