### ISSUE TITLE
Intercept onNext for validation

### ISSUE THREAD

**Issue by yuskamal** [colbymillerdev/react-native-progress-steps#3]
it's posibble to intercept onNext button for validation before it's going to next step ?

**Comment by colbymillerdev** [comment]
Thanks for bringing up this issue! Currently, there isn't a way to stop the onNext prop from moving to the next step when it's called.

I will add this functionality later today and push a new build once completed.

For now, the option is to disable the next button using the `nextBtnDisabled` prop until all your required validations have passed.

**Comment by colbymillerdev** [comment]
This issue has been resolved by introducing an `errors` prop. If set to true, the next step won't be rendered when clicking the next button.

Please refer to the new "Current Step Error and Validation Handling" section in the [README](https://github.com/colbymillerdev/react-native-progress-steps#readme) file for an example.
