### ISSUE TITLE
Want to customise into a Dynamic React Native Stepper

### ISSUE THREAD

**Issue by keyurpatel8118** [colbymillerdev/react-native-progress-steps#31]
In this stepper, the issue I am running with is, the number of steps to be provided to the stepper is obtained at run time (dynamic). Hence, in this case, how should I progress. Can anybody help?

**Comment by colbymillerdev** [comment]
Hello - Can you explain a bit more about what you're trying to achieve? Thanks!

**Comment by keyurpatel8118** [comment]
Basically I was trying to say that the number of steps in the stepper would be known to me during the run time of App. And for the same I was asking a solution. 
But finally I could achieve this using **Map** in javascript.
Thanks!
