### ISSUE TITLE
Invalid props.style key `textAlign` supplied to `View`

### ISSUE THREAD

**Issue by angelomedina** [colbymillerdev/react-native-progress-steps#32]
"react-native-progress-steps": "^1.2.9",Implementing errorWarning: 

Failed prop type: Invalid props.style key `textAlign` supplied to `View`.Bad object: {  "transitionProperty": "opacity",  "transitionDuration": "0.15s",  "userSelect": "none",  "cursor": "pointer",  "touchAction": "manipulation",  "textAlign": "center",  "padding": 8}Valid keys: [  "animationDelay",  "animationDirection",  "animationDuration",  "animationFillMode",  "animationIterationCount",  "animationKeyframes",  "animationPlayState",  "animationTimingFunction",  "transitionDelay",  "transitionDuration",  "transitionProperty",  "transitionTimingFunction",  "borderColor",  "borderBottomColor",  "borderEndColor",  "borderLeftColor",  "borderRightColor",  "borderStartColor",  "borderTopColor",  "borderRadius",  "borderBottomEndRadius",  "borderBottomLeftRadius",  "borderBottomRightRadius",  "borderBottomStartRadius",  "borderTopEndRadius",  "borderTopLeftRadius",  "borderTopRightRadius",  "borderTopStartRadius",  "borderStyle",  "borderBottomStyle",  "borderEndStyle",  "borderLeftStyle",  "borderRightStyle",  "borderStartStyle",  "borderTopStyle",  "cursor",  "touchAction",  "userSelect",  "willChange",  "alignContent",  "alignItems",  "alignSelf",  "backfaceVisibility",  "borderWidth",  "borderBottomWidth",  "borderEndWidth",  "borderLeftWidth",  "borderRightWidth",  "borderStartWidth",  "borderTopWidth",  "bottom",  "boxSizing",  "direction",  "display",  "end",  "flex",  "flexBasis",  "flexDirection",  "flexGrow",  "flexShrink",  "flexWrap",  "height",  "justifyContent",  "left",  "margin",  "marginBottom",  "marginHorizontal",  "marginEnd",  "marginLeft",  "marginRight",  "marginStart",  "marginTop",  "marginVertical",  "maxHeight",  "maxWidth",  "minHeight",  "minWidth",  "order",  "overflow",  "overflowX",  "overflowY",  "padding",  "paddingBottom",  "paddingHorizontal",  "paddingEnd",  "paddingLeft",  "paddingRight",  "paddingStart",  "paddingTop",  "paddingVertical",  "position",  "right",  "start",  "top",  "visibility",  "width",  "zIndex",  "aspectRatio",  "gridAutoColumns",  "gridAutoFlow",  "gridAutoRows",  "gridColumnEnd",  "gridColumnGap",  "gridColumnStart",  "gridRowEnd",  "gridRowGap",  "gridRowStart",  "gridTemplateColumns",  "gridTemplateRows",  "gridTemplateAreas",  "shadowColor",  "shadowOffset",  "shadowOpacity",  "shadowRadius",  "shadowSpread",  "perspective",  "perspectiveOrigin",  "transform",  "transformOrigin",  "transformStyle",  "backgroundColor",  "opacity",  "elevation",  "backdropFilter",  "backgroundAttachment",  "backgroundBlendMode",  "backgroundClip",  "backgroundImage",  "backgroundOrigin",  "backgroundPosition",  "backgroundRepeat",  "backgroundSize",  "boxShadow",  "clip",  "filter",  "outlineColor",  "outlineOffset",  "outlineStyle",  "outlineWidth",  "overscrollBehavior",  "overscrollBehaviorX",  "overscrollBehaviorY",  "scrollbarWidth",  "scrollSnapAlign",  "scrollSnapType",  "WebkitMaskImage",  "WebkitOverflowScrolling"]    in View (created by TouchableOpacity)    in TouchableOpacity (at ProgressStep.js:83)    in div (created by View)    in View (at ProgressButtons.js:6)    in div (created by View)    in View (at ProgressButtons.js:5)    in ProgressButtons (at ProgressStep.js:96)    in div (created by View)    in View (at ProgressStep.js:93)    in ProgressStep (at register_buyer/index.tsx:68)    in div (created by View)    in View (at ProgressSteps.js:67)    in div (created by View)    in View (at ProgressSteps.js:65)    in ProgressSteps (at register_buyer/index.tsx:60)    in div (created by View)    in View (at register_buyer/index.tsx:58)    in RegisterBuyerScreen (created by SceneView)    in SceneView (created by CardContainer)    in div (created by View)    in View (created by CardContainer)    in div (created by View)    in View (created by CardContainer)    in div (created by View)    in View (created by Card)    in div (created by View)    in View (created by AnimatedComponent)    in AnimatedComponent (created by PanGestureHandler)    in PanGestureHandler (created by Card)    in div (created by View)    in View (created by AnimatedComponent)    in AnimatedComponent (created by Card)    in div (created by View)    in View (created by Card)    in Card (created by CardContainer)    in CardContainer (created by CardStack)    in div (created by View)    in View (created by AnimatedComponent)    in AnimatedComponent (at screens.web.js:105)    in Screen (created by MaybeScreen)    in MaybeScreen (created by CardStack)    in div (created by View)    in View (created by MaybeScreenContainer)    in MaybeScreenContainer (created by CardStack)    in CardStack (created by KeyboardManager)    in KeyboardManager (created by Context.Consumer)    in SafeAreaProviderCompat (created by StackView)    in div (created by View)    in View (created by StackView)    in StackView (created by StackView)    in StackView    in Unknown (created by Navigator)    in Navigator (created by SceneView)    in SceneView (created by SwitchView)    in SwitchView (created by Navigator)    in Navigator (created by NavigationContainer)    in NavigationContainer (at App.tsx:9)    in div (created by View)    in View (at NativeSafeAreaView.web.tsx:58)    in NativeSafeAreaView (at src/index.tsx:26)    in SafeAreaProvider (at App.tsx:8)    in App (at withExpoRoot.web.js:13)    in RootErrorBoundary (at withExpoRoot.web.js:12)    in ExpoRootComponent (at registerRootComponent.web.js:6)    in RootComponent    in div (created by View)    in View (created by AppContainer)    in div (created by View)    in View (created by AppContainer)    in AppContainer
-- | --

**Comment by colbymillerdev** [comment]
Hello - What is the exact issue you are experiencing? It is difficult to determine based on this output.

**Comment by lcmr** [comment]
Hi, i had the same error, to fix it, just go to the ProgressStep.js, find the function renderNextButton and renderPreviousButton and remove this **textAlign: 'center'** in the styles

**Comment by angelomedina** [comment]
Hi ??, thanks so much for this tip.On Fri, Apr 24, 2020 at 7:34 PM Luis Mendez <notifications@github.com> wrote:
Hi, i had the same error, to fix it, just go to the ProgressStep.js, find the function renderNextButton and renderPreviousButton and remove this textAlign: 'center' in the styles

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
