### ISSUE TITLE
react-native-progress-steps Prop updates

### ISSUE THREAD

**Issue by curtismenmuir** [colbymillerdev/react-native-progress-steps#39]
Hi there,
Thanks for publicly sharing this repo! ❤️ 

I am needing the following updates:
- Prop to set the completed labels font color (separate to the disabled label color)
- Prop to completely hide the ProgressStep buttons
- activeStep updated so that it supports changing values
-  A prop so that all Steps can be set to complete stage (all showing the completed tick).
-  A prop so that all Steps can be set to failure stage (all showing the failure cross).

**Comment by curtismenmuir** [comment]
Added PR with fixes for all: https://github.com/colbymillerdev/react-native-progress-steps/pull/38

**Comment by curtismenmuir** [comment]
Happy to split PR if required

**Comment by curtismenmuir** [comment]
Working on PR for this, will send across when ready

**Comment by curtismenmuir** [comment]
PR: https://github.com/colbymillerdev/react-native-progress-steps/pull/38

**Comment by colbymillerdev** [comment]
I am going to close this issue so we can continue conversation in the PR 🙂
