### ISSUE TITLE
Hide Progress Button (previous, next) section

### ISSUE THREAD

**Issue by developer-anilpatidar** [colbymillerdev/react-native-progress-steps#4]
Can we Hide footer section it's tacking much space.

**Comment by colbymillerdev** [comment]
There isn't a prop to do this, however you can pass the css property `display: 'none'` to the `nextBtnTextStyle` and `previousBtnTextStyle` props. Refer to the [https://github.com/colbymillerdev/react-native-progress-steps#button-styling-usage](Button Styling Usage) section of the readme file to see how to pass styles to these props.

**Comment by colbymillerdev** [comment]
There isn't a prop to do this, however you can pass the css property `display: 'none'` to the `nextBtnTextStyle` and `previousBtnTextStyle` props. Refer to the [Button Styling Usage](https://github.com/colbymillerdev/react-native-progress-steps#button-styling-usage) section of the readme file to see how to pass styles to these props.

**Comment by waly2020** [comment]
How to hide number progresse ? i want just have the buttons (next and previou) and the content of curent step not numbers of top
