### ISSUE TITLE
hi. how can i flip the horizontal direction of the steps? couldnt find it.

### ISSUE THREAD

**Issue by baryanuka** [colbymillerdev/react-native-progress-steps#40]

**Comment by colbymillerdev** [comment]
Hello -

Currently the steps can only be aligned horizontally. There isn't an ability for vertically aligned steps at this time.

**Comment by baryanuka** [comment]
hi colby thank u for your answer. what i meant is to flip just the direction from horizontally right to left and horizontally left to right.  is there any option to do it? right now it let me only use it right to left not like in your example and i dont understand why?   thx again

**Comment by baryanuka** [comment]
i have another question please. how can i reduce the space between the next/previous buttons to the steps bar
