### ISSUE TITLE
Warning Using Progress Steps VirtualizedLists should never be nested inside plain ScrollViews

### ISSUE THREAD

**Issue by netmas** [colbymillerdev/react-native-progress-steps#46]
Hi! I just updated expo from sdk 35 to 37. Since that I'm getting this error:

VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.

My code looks like this:

`<SafeAreaView style={{flex:1}}>
				<KeyboardAvoidingView
					behavior={Platform.OS === "ios" ? "padding" : "position"}
					enabled
				>
					<ScrollView>
						<Appbar.Header>
							<Appbar.Action icon="menu" onPress={() => this.props.navigation.toggleDrawer()} />
							<Appbar.Content
								title="Mi Bascula GaMa"
								subtitle="Registro De Trabajo"
							/>
							<Appbar.Action icon="dots-vertical" onPress={this._onMore} />
						</Appbar.Header>
						<ProgressSteps>
                            <ProgressStep 
								label="Registros De Trabajo"
								onNext={ () => console.log("Funciona!!")}
								errors={this.state.errors} 
								previousBtnText = {`Anterior`}
								nextBtnText = {`Siguiente`} >
								<Divider />
								<FlatList
								keyExtractor={this.keyExtractor}
								data={ showingBasculas }
								renderItem={this.renderItem}
								ListEmptyComponent = { <Paragraph style={{ alignSelf : 'center', paddingTop: 50 }}>No hay registros de trabajo disponibles</Paragraph> }
								/>
								<DialogSiNoObject
									visible = {this.state.visible_dialog_generar_reporte_trabajo} 
									data = {this.state.data}
								/>

							</ProgressStep>
							<ProgressStep 
								label="Reportes Generados"
								onNext={ () => console.log("Funciona!!")}
								errors={this.state.errors} 
								previousBtnText = {`Anterior`}
								finishBtnText = {`Salir`}
								onSubmit={()=>{this.props.navigation.goBack()}} >
								<Divider />
								<FlatList
								keyExtractor={this.keyExtractorInformeTecnicoCab}
								data={ showingInformeTecnicoCab }
								renderItem={this.renderItemInformeTecnicoCab}
								ListEmptyComponent = { <Paragraph style={{ alignSelf : 'center', paddingTop: 50 }}>No data available</Paragraph> }
								/>
								
							</ProgressStep>
						</ProgressSteps> 
						
					</ScrollView>
                </KeyboardAvoidingView>
          	</SafeAreaView>`

I've trie removing the main ScrollView, but I think the ProgressStep component is a ScrollView. Can you help me with this?

**Comment by dl-husky73** [comment]
Did you fix this issue, I am facing the same issue.  I did the first 4 steps but forgot the 5th step had a flatlist.   Wondering how you resolved?

**Comment by colbymillerdev** [comment]
Hello -

This should now be fixed by adding the `scrollable={false}` prop to the `ProgressStep` component. This will replace the ScrollView with a View internally. Refer to PR #50 for the code change.

**Comment by dl-husky73** [comment]
Awesome!  I will try it tomorrow morning and let you know outcome!  Again, thanks for all the hard work.
