### ISSUE TITLE
ScrollView inside ProgressStep

### ISSUE THREAD

**Issue by dl-husky73** [colbymillerdev/react-native-progress-steps#52]
I have a ScrollView inside the ProgressStep but I can't scroll to the bottom.  I have tried all sorts of settings to the ScrollView.  The Form has a TextInput that grows with content.  The form looks fine and scrolls correctly outside of ProgressStep (Part of a Wizard and then can be modified outside wizard)

I see ScrollViewProps and wondering how to manage?

**Comment by colbymillerdev** [comment]
Hi @dl-husky73 !

The `ProgressStep` component already uses a ScrollView internally, so you shouldn't need to place another ScrollView inside of it. Try removing the one added and see if that helps.

**Comment by dl-husky73** [comment]
That worked!  Thanks.  I like this package, making a great registration wizard, thanks for the great work.  Also, I saw the pr on view instead of ScrollView, I have a flatlist that is giving me a warning.  Can you push that commit?

**Comment by colbymillerdev** [comment]
@dl-husky73 Thats great to hear! Glad you're finding it useful and thanks for choosing to use it in your project 🙂

I am taking a look at that PR now. I'll get it merged and push a new release to npm shortly.

**Comment by colbymillerdev** [comment]
Version 1.3.3 of the package has been published to npm. I'm also going to go ahead and close this issue.
