### ISSUE TITLE
Add option for inner "Next"

### ISSUE THREAD

**Issue by YuvApps** [colbymillerdev/react-native-progress-steps#56]
hey,

I'd like to use your "Next" and "Previous" buttons' logic in my inner child of "Progress Step" but I couldn't figure out how to do that..

I'd like for your help.
Thanks

**Comment by AndresMontoya03** [comment]
+1

**Comment by colbymillerdev** [comment]
Hello - The `onNext` and `onPrevious` props can be used on the `ProgressStep` component to call the next/previous buttons.
