### ISSUE TITLE
Restart stepper on submit

### ISSUE THREAD

**Issue by OsainAbitia** [colbymillerdev/react-native-progress-steps#67]
Hi! I'm trying to restart stepper when the user press the submit button in final step, I've tried updating the currentStep with useState but isn't rendering. Am I missing something?

Thanks in advance!

**Comment by elielcena** [comment]
UP!

**Comment by edwinsmasher** [comment]
<ProgressSteps activeStep={this.state.currentStep}>
</ProgressSteps >
onSubmit => set currentStep to 0

**Comment by abdodeve** [comment]
> `<ProgressSteps activeStep={this.state.currentStep}> </ProgressSteps >`
> onSubmit => set currentStep to 0

Thank you that's work for me 

I added this
`const [currentStep, setCurrentStep] = useState(0);`

And at the last step
    ```
  onSubmit={() => {
              // Reset
              setCurrentStep(0);
            }}
```

**Comment by OsainAbitia** [comment]
Great!, I'm closing this issue, thanks!

**Comment by BryanTacuri** [comment]
Hello, I have the same problem but @abdodeve  comment doesn't work for me :(. Could you help me?
I attach my code: 
`const [currentStep, setCurrentStep] = useState(0);

  return (
    <View style={{flex: 1, backgroundColor: '#fff'}}>
      <ProgressSteps activeStep={currentStep}>
        <ProgressStep>
          <Text>Step 1</Text>
        </ProgressStep>
        <ProgressStep>
          <View style={{alignItems: 'center'}}>
            <Text
              style={{
                fontSize: 18,
                color: '#333C83',
                fontWeight: 'bold',
                textAlign: 'center',
              }}>
              VENTANA PAGO
            </Text>
          </View>
        </ProgressStep>

        <ProgressStep onSubmit={() => setCurrentStep(0)}>
          <View style={{alignItems: 'center'}}>
            <Text
              style={{
                fontSize: 18,
                color: '#333C83',
                fontWeight: 'bold',
                textAlign: 'center',
              }}>
              Suscripción generada exitosamente
            </Text>
          </View>
        </ProgressStep>
      </ProgressSteps>
    </View>
  );
}`

**Comment by BryanTacuri** [comment]
Hello, I have the same problem but @abdodeve's comment doesn't work for me :(. Could you help me?
I attach my code:
`const [currentStep, setCurrentStep] = useState(0);

  return (
    <View style={{flex: 1, backgroundColor: '#fff'}}>
      <ProgressSteps activeStep={currentStep}>
        <ProgressStep>
          <Text>Step 1</Text>
        </ProgressStep>
        <ProgressStep>
          <View style={{alignItems: 'center'}}>
            <Text
              style={{
                fontSize: 18,
                color: '#333C83',
                fontWeight: 'bold',
                textAlign: 'center',
              }}>
              VENTANA PAGO
            </Text>
          </View>
        </ProgressStep>

        <ProgressStep onSubmit={() => setCurrentStep(0)}>
          <View style={{alignItems: 'center'}}>
            <Text
              style={{
                fontSize: 18,
                color: '#333C83',
                fontWeight: 'bold',
                textAlign: 'center',
              }}>
              Suscripción generada exitosamente
            </Text>
          </View>
        </ProgressStep>
      </ProgressSteps>
    </View>
  );
}`

**Comment by BryanTacuri** [comment]
Hello, I have the same problem but @abdodeve's comment doesn't work for me :(. Could you help me?
I attach my code:
const [currentStep, setCurrentStep] = useState(0);

  `return (

    <View >
      <ProgressSteps activeStep={currentStep}>
        <ProgressStep>
          <Text>Step 1</Text>
        </ProgressStep>
        <ProgressStep>
          <View >
            <Text>
              VENTANA PAGO
            </Text>
          </View>
        </ProgressStep>
        <ProgressStep onSubmit={() => setCurrentStep(0)}>
          <View>
            <Text>
              Suscripción generada exitosamente
            </Text>
          </View>
        </ProgressStep>
      </ProgressSteps>
    </View>
  );
}`
