### ISSUE TITLE
incompatible with typescripte

### ISSUE THREAD

**Issue by samir0067** [colbymillerdev/react-native-progress-steps#73]
Hello I am working on a react native project in typescript,

`import { ProgressSteps, ProgressStep } from 'react-native-progress-steps'`

it and impossible to import the library here is the error message:

`TS7016: Could not find a declaration file for module 'react-native-progress-steps`

and the command does not work

`yarn add @types/react-native-progress-steps`

did you have a solution thank you

**Comment by abdulghanitech** [comment]
Hello, @samir0067 I would like to how did you solve this issue? Because I'm facing the same issue.
